
import "./globals.css";
import Provider from "./components/provider";
import Navbar from "./components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClientSessionWrapper>{children} </ClientSessionWrapper>
      </body>
    </html>
  );
}

function ClientSessionWrapper({children}){
  "use client"
  return <Provider>
    <Navbar />
        {children}
    </Provider>
}
